name: "🚀 release"

on:
  release:
    types: [published]

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: 🚀 publish
        run: npm publish --access public
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
